# Generated by Django 3.0.5 on 2021-05-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sii_Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idApp', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(default='', max_length=70)),
                ('valeur', models.TextField(default='')),
                ('alerte', models.IntegerField(default=0)),
                ('messageAlerte', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
